# Generated by Django 2.1 on 2018-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='article_type',
            field=models.CharField(blank=True, choices=[('DRF', 'Django Rest Framework'), ('TF', 'Tensor Flow'), ('RJ', 'React JavaScript')], max_length=3, verbose_name='type'),
        ),
    ]
